"""
AI Refiner — Gemini-powered code refinement (NO SVG output)
=============================================================
Takes skeleton code + original image + structured JSON and asks
Gemini to refine styling, spacing, and visual fidelity.

CRITICAL CONSTRAINT:
  - Output must use ONLY: div, button, input, img, p, h1, h2
  - ABSOLUTELY NO: svg, canvas, path, circle, rect, polygon, line

Key principle: Gemini REFINES the skeleton — it does NOT recreate from scratch.
"""

import os
import re
import json
from PIL import Image


def refine_with_ai(client, model, image_path, skeleton_code, layout_json, framework='html-css'):
    """
    Use Gemini to refine the skeleton code based on the original image.

    Args:
        client: google.genai Client instance.
        model (str): Model name (e.g., 'gemini-3-flash-preview').
        image_path (str): Path to the original screenshot.
        skeleton_code (str): The skeleton code generated by generator.py.
        layout_json (dict): The structured layout JSON from parser.py.
        framework (str): Target framework.

    Returns:
        str: Refined code with improved styling (no SVG/canvas).
    """
    img = Image.open(image_path)

    prompt = _build_refinement_prompt(skeleton_code, layout_json, framework)

    response = client.models.generate_content(
        model=model,
        contents=[prompt, img]
    )

    refined_code = response.text.strip()

    # Clean markdown fences
    refined_code = _clean_code_fences(refined_code, framework)

    # SAFETY: Strip any SVG/canvas tags that Gemini might have added
    refined_code = _strip_forbidden_tags(refined_code)

    return refined_code


def _build_refinement_prompt(skeleton_code, layout_json, framework):
    """
    Build a refinement prompt that STRICTLY forbids SVG/canvas output.
    """
    structure_summary = json.dumps(layout_json, indent=2)

    # Framework-specific output rules
    if framework == 'react-tailwind':
        format_rules = """
OUTPUT FORMAT:
- Output ONLY the JSX code — NO markdown fences, NO explanations
- Keep it as a single default export React component
- Use ONLY Tailwind CSS utility classes
- All className attributes must use double quotes"""
    elif framework == 'tailwind-css':
        format_rules = """
OUTPUT FORMAT:
- Output ONLY the complete HTML file — NO markdown fences, NO explanations
- Start with <!DOCTYPE html>, end with </html>
- Keep the Tailwind CDN script tag
- Use ONLY Tailwind CSS utility classes"""
    else:
        format_rules = """
OUTPUT FORMAT:
- Output ONLY the complete HTML file — NO markdown fences, NO explanations
- Start with <!DOCTYPE html>, end with </html>
- ALL CSS must be inside a <style> tag in <head>
- Use Google Fonts for modern typography"""

    return f"""You are a UI refinement assistant. I have already analyzed a UI screenshot and detected these semantic components:

DETECTED STRUCTURE:
{structure_summary}

SKELETON CODE (already generated):
{skeleton_code}

YOUR TASK:
Look at the original screenshot image and IMPROVE the skeleton code above.

WHAT TO IMPROVE:
1. Match exact colors, gradients, and shadows from the screenshot
2. Fix spacing, padding, and margins to match the original
3. Add the actual text content visible in the screenshot
4. Improve typography (font sizes, weights, letter-spacing)
5. Add hover effects and smooth transitions on buttons
6. Make it responsive

CRITICAL CONSTRAINTS — YOU MUST FOLLOW THESE:
- Use ONLY these HTML tags: div, button, input, img, p, h1, h2, h3, span, a, header, main, footer, section, nav, ul, li, label, form
- ABSOLUTELY DO NOT USE: <svg>, <canvas>, <path>, <circle>, <rect>, <polygon>, <line>, <polyline>, <ellipse>, <g>, <defs>, <use>, <symbol>
- For icons, use Unicode emoji characters (e.g. ✓ ✕ ⚡ 📧 🔍) — NEVER inline SVG
- For decorative elements, use CSS (borders, shadows, gradients, border-radius) — NEVER SVG
- For images, use <img> with placeholder src or styled <div> — NEVER SVG
- This is a HARD REQUIREMENT. Any SVG or canvas in your output is a FAILURE.

WHAT NOT TO CHANGE:
- Do NOT change the overall page structure/layout
- Do NOT remove detected components
- Do NOT add major new sections not in the screenshot
- Keep the semantic HTML component mapping (buttons stay as <button>, inputs as <input>, etc.)

{format_rules}

Generate the improved code now:"""


def _clean_code_fences(code, framework):
    """Remove markdown code fences if present."""
    code = re.sub(r'^```(?:html|jsx|javascript|tsx|js|css)?\s*\n?', '', code, flags=re.IGNORECASE)
    code = re.sub(r'\n?```\s*$', '', code)
    code = code.strip()

    if framework in ('html-css', 'tailwind-css'):
        if not code.lower().startswith('<!doctype'):
            match = re.search(r'(<!DOCTYPE html>.*?</html>)', code, re.DOTALL | re.IGNORECASE)
            if match:
                code = match.group(1)

    return code


def _strip_forbidden_tags(code):
    """
    Safety net: remove any SVG, canvas, or vector tags that Gemini
    might have sneaked in despite the prompt instructions.
    """
    # Remove complete <svg>...</svg> blocks
    code = re.sub(r'<svg[^>]*>.*?</svg>', '', code, flags=re.DOTALL | re.IGNORECASE)

    # Remove complete <canvas>...</canvas> blocks
    code = re.sub(r'<canvas[^>]*>.*?</canvas>', '', code, flags=re.DOTALL | re.IGNORECASE)

    # Remove self-closing SVG element tags like <path .../>, <circle .../>, etc.
    svg_tags = ['path', 'circle', 'rect', 'polygon', 'line', 'polyline', 'ellipse', 'g', 'defs', 'use', 'symbol']
    for tag in svg_tags:
        code = re.sub(rf'<{tag}[^>]*/>', '', code, flags=re.IGNORECASE)
        code = re.sub(rf'<{tag}[^>]*>.*?</{tag}>', '', code, flags=re.DOTALL | re.IGNORECASE)

    return code
